# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	project 'mobApp.xcodeproj'
	pod 'Firebase'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Charts'

  # Pods for mobApp

  target 'mobAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
